# stage 1 building the angular app
FROM node:latest as node
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build 

# stage 2 running the angular app
FROM nginx:alpine
COPY --from=node /app/dist/weather-app /usr/share/nginx/html
